# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  BOX_IMAGE = "bento/ubuntu-20.04"
  K3S_VERSION = "v1.24.15+k3s1"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 1536
    
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  
  config.vm.box_check_update = false
  config.vm.boot_timeout = 600
  
  config.vm.define "yichanS" do |server|
    server.vm.box = BOX_IMAGE
    server.vm.hostname = "yichanS"
    
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant", disabled: true
    server.vm.provision "file", source: "conf", destination: "/home/vagrant/conf"

    server.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update -y
      sudo apt-get install -y curl apt-transport-https

      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="#{K3S_VERSION}" INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -

      sudo ln -sf /usr/local/bin/kubectl /usr/bin/kubectl      
      
      echo "Waiting for K3s to generate kubeconfig..."
      while [ ! -f /etc/rancher/k3s/k3s.yaml ]; do
        sleep 2
      done
      
      mkdir -p /home/vagrant/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      sudo chown vagrant:vagrant /home/vagrant/.kube/config
      
      echo 'export KUBECONFIG=~/.kube/config' >> /home/vagrant/.bashrc
      echo 'alias k=kubectl' >> /home/vagrant/.bashrc
    SHELL

    server.vm.provision "shell", inline: <<-SHELL
      export KUBECONFIG=/home/vagrant/.kube/config
      
      while ! kubectl get nodes | grep -q "Ready"; do
        echo "Waiting for node yichanS to report Ready status..."
        sleep 5
      done
      
      echo "Applying Kubernetes configurations..."
      kubectl apply -f /home/vagrant/conf
    SHELL
  end
end