# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  BOX_IMAGE = "ubuntu/xenial64"
  K3S_VERSION = "v1.24.15+k3s1"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end
  
  config.vm.box_check_update = false
  
  config.vm.define "yichanS" do |server|
    server.vm.box = BOX_IMAGE
    server.vm.hostname = "yichanS"
    
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant", disabled: true
    server.vm.provision "file", source: "conf", destination: "/home/vagrant/conf"


    server.vm.provision "shell", inline: <<-SHELL
 
      sudo apt-get update -y
      sudo apt-get install -y curl apt-transport-https

      curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="#{K3S_VERSION}" INSTALL_K3S_EXEC="--node-ip=192.168.56.110" sh -

      sudo ln -sf /usr/local/bin/kubectl /usr/bin/kubectl      
      
      mkdir -p /home/vagrant/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      echo 'export KUBECONFIG=~/.kube/config' >> /home/vagrant/.bashrc
      echo 'alias k=kubectl' >> /home/vagrant/.bashrc
      # Wait for k3s to be ready
      sleep 10
      chown --recursive vagrant:vagrant /home/vagrant
      chown --recursive vagrant:vagrant /etc/rancher/k3s
    SHELL

    server.vm.provision "shell", inline: <<-SHELL
      # Wait for k3s to be fully ready
      while ! kubectl get nodes &> /dev/null; do
        echo "Waiting for k3s to be ready..."
        sleep 5
      done
      
      echo "Applying Kubernetes configurations..."
      kubectl apply -f /home/vagrant/conf
    SHELL
  end
end
